game:
  tick: 10
  rows: 20
  cols: 20
  snake:
    color: "green"
  food:
    color: "red"
window:
  title: "Snake Game"
  width: 800
  height: 800
  background:
    color: "black"
  grid:
    color: "#3c3c3b"
font:
  name: "arial"
  size: 60
  color: "white"
